apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nginx
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        
        server {
            listen 80;
            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
            }
            
            location /nginx_status {
                stub_status on;
                access_log off;
                allow all;
            }
        }
    }