apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-script
  namespace: k6-load
data:
  load-test.js: |
    import http from 'k6/http';
    import { check } from 'k6';

    export let options = {
      scenarios: {
        constant_arrival_rate: {
          executor: 'constant-arrival-rate',
          rate: 1000, // 1000 iterations per second (1000 TPS)
          timeUnit: '1s',
          duration: '10m',
          preAllocatedVUs: 50, // how many VUs to pre-allocate
          maxVUs: 500, // maximum VUs to spawn
        },
      },
    };

    export default function () {
      let response = http.get('http://istio-ingress.istio-ingress.svc.cluster.local/nginx');
      
      check(response, {
        'status is 200': (r) => r.status === 200,
        'response time < 500ms': (r) => r.timings.duration < 500,
      });
      
    }