apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6-load-test
  namespace: k6-load
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k6-load-test
  template:
    metadata:
      labels:
        app: k6-load-test
    spec:
      containers:
      - name: k6
        image: grafana/k6:latest
        command: ["k6", "run", "--out", "experimental-prometheus-rw", "/scripts/load-test.js"]
        ports:
        - containerPort: 5656
          name: metrics
        volumeMounts:
        - name: k6-script
          mountPath: /scripts
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: k6-script
        configMap:
          name: k6-script
