apiVersion: v1
kind: Service
metadata:
  name: k6-load-test
  namespace: k6-load
  labels:
    app: k6-load-test
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5656"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: k6-load-test
  ports:
  - name: metrics
    port: 5656
    targetPort: 5656
    protocol: TCP
  type: ClusterIP