apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mohamediag/aks-terraform-cilium
    targetRevision: HEAD
    path: gitops-apps/argo-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true