---
# Source: kube-prometheus-stack/charts/grafana/templates/clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    helm.sh/chart: grafana-9.3.2
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: prometheus-operator
    app.kubernetes.io/version: "12.1.0"
  name: prometheus-operator-grafana-clusterrole
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["configmaps", "secrets"]
    verbs: ["get", "watch", "list"]
