---
# Source: kube-prometheus-stack/charts/grafana/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-operator-grafana
  namespace: prometheus-operator
  labels:
    helm.sh/chart: grafana-9.3.2
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: prometheus-operator
    app.kubernetes.io/version: "12.1.0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-operator-grafana
subjects:
- kind: ServiceAccount
  name: prometheus-operator-grafana
  namespace: prometheus-operator
