apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    istio-injection: enabled
    istio.io/rev: default
    app.kubernetes.io/name: istio-system
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/version: "1.27.0"
    helm.sh/chart: istio-1.27.0

---

apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
  labels:
    istio-injection: enabled
